<a href="https://colab.research.google.com/github/JGH94/Python_Pandas/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from numpy import nan as NA 

In [ ]:
# 기초 Series, DataFrame
# Series는 1차원 배열 구조 배열에대한 색인을 갖고있음
# DataFrame은 로우와 컬럼에 대한 색인을 가지고 있으며, 파이썬 DIct와 비슷하다
# 색인 객체는 변경이 불가능, reindex를 사용하여 야함 
series = pd.Series([1,5,-5,3])
print(series) 
dataframe = pd.DataFrame({1,5,-5,3})
dataframe

0    1
1    5
2   -5
3    3
dtype: int64


0
0  3
1  1
2 -5
3  5

In [ ]:
# excel, Josn 형태의 다양한 형태의 데이터를 사용.. json 형태의 데이터를 받는 형태
import json
json_ = """ {  "name": "WECO",
               "addr": "SEONGNAM",
               "friends" : [{"name" : "J", "AGE" : 29},
                            {"name" : "K", "AGE" : 25}]}"""
a_json = json.loads(json_) # python 형태로 변환 
b_json = json.dumps(a_json)# python 객체를 json형태로 변환
print(a_json,type(a_json))
print(b_json,type(b_json))

# json 형태를 DataFrame으로 가져옴
c_json = pd.DataFrame(a_json['friends'], columns = ["name","AGE"]) 
c_json 

{'name': 'WECO', 'addr': 'SEONGNAM', 'friends': [{'name': 'J', 'AGE': 29}, {'name': 'K', 'AGE': 25}]} <class 'dict'>
{"name": "WECO", "addr": "SEONGNAM", "friends": [{"name": "J", "AGE": 29}, {"name": "K", "AGE": 25}]} <class 'str'>


name  AGE
0    J   29
1    K   25

In [ ]:
# null 값 제거 
#Series
print('1.Series') 
Slist_ = pd.Series([1,NA,3,NA,5,NA, 7])
print(Slist_)
print('-------------------------------------------')
print(Slist_.dropna()) 
#DataFrame
print('2.DataFrame') 
Dlist_ = pd.DataFrame([[1,5,3],[1,NA,5],[NA,NA,NA],[NA,5,3]])
print(Dlist_)
print('-------------------------------------------') 
#null 값을 하나라도 포함하면 제거
print('3.null 값을 하나라도 포함하면 제거') 
Dlist_D = Dlist_.dropna();
print(Dlist_D)
print('-------------------------------------------') 
#null 값이 전부인 로우만 제거
print('4. null 값이 전부인 로우만 제거') 
Dlist_R = Dlist_.dropna(how='all')
print(Dlist_R)
print('-------------------------------------------') 
#Col도 적용가능
print('5. Col도 적용가능') 
Dlist_[4] = NA # 4번째 컬럼에 null 값 적용
print(Dlist_)
Dlist_C = Dlist_.dropna(how='all', axis=1)
print(Dlist_C) 

1.Series
0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    NaN
6    7.0
dtype: float64
-------------------------------------------
0    1.0
2    3.0
4    5.0
6    7.0
dtype: float64
2.DataFrame
     0    1    2
0  1.0  5.0  3.0
1  1.0  NaN  5.0
2  NaN  NaN  NaN
3  NaN  5.0  3.0
-------------------------------------------
3.null 값을 하나라도 포함하면 제거
     0    1    2
0  1.0  5.0  3.0
-------------------------------------------
4. null 값이 전부인 로우만 제거
     0    1    2
0  1.0  5.0  3.0
1  1.0  NaN  5.0
3  NaN  5.0  3.0
-------------------------------------------
5. Col도 적용가능
     0    1    2   4
0  1.0  5.0  3.0 NaN
1  1.0  NaN  5.0 NaN
2  NaN  NaN  NaN NaN
3  NaN  5.0  3.0 NaN
     0    1    2
0  1.0  5.0  3.0
1  1.0  NaN  5.0
2  NaN  NaN  NaN
3  NaN  5.0  3.0


In [ ]:
# 결측치 
dt_ = pd.DataFrame(np.random.randn(7,3))
dt_.iloc[:4,1] = NA
dt_.iloc[:2,2] = NA
print(dt_)
print('------------------------------\r\n')
print('1. 0으로 채우기')
print(dt_.fillna(0))
print('------------------------------\r\n') 
print('2. 컬럼마다 다른 값 적용')
print(dt_.fillna({1:1, 2:0}))
print('------------------------------\r\n') 
print('3. 평균값')
print(dt_.fillna(dt_.mean(),limit=2)) # limit은 앞의 몇개, 뒤에 몇개부터 값을 채울지 지정

          0         1         2
0 -0.130121       NaN       NaN
1  0.033178       NaN       NaN
2 -0.407143       NaN -0.028968
3  1.044228       NaN -0.355387
4 -0.544153 -0.830487  0.100461
5  0.165255  0.758966  0.277584
6  0.662416 -0.443102 -0.832754
------------------------------

1. 0으로 채우기
          0         1         2
0 -0.130121  0.000000  0.000000
1  0.033178  0.000000  0.000000
2 -0.407143  0.000000 -0.028968
3  1.044228  0.000000 -0.355387
4 -0.544153 -0.830487  0.100461
5  0.165255  0.758966  0.277584
6  0.662416 -0.443102 -0.832754
------------------------------

2. 컬럼마다 다른 값 적용
          0         1         2
0 -0.130121  1.000000  0.000000
1  0.033178  1.000000  0.000000
2 -0.407143  1.000000 -0.028968
3  1.044228  1.000000 -0.355387
4 -0.544153 -0.830487  0.100461
5  0.165255  0.758966  0.277584
6  0.662416 -0.443102 -0.832754
------------------------------

3. 평균값
          0         1         2
0 -0.130121 -0.171541 -0.167813
1  0.033178 -0.171541 -0.167813
2 -0.4

In [ ]:
# 중복제거
list_ = pd.DataFrame({"A":["one","tow"] * 3 + ["tow"],
                      "B":["-999","1","2","2","-999","4","4"]})
print(list_) 
print('------------------------------\r\n')  
print(list_.duplicated())      # 중복인 항목을 Bool 형태로 반환
print('------------------------------\r\n')  
print(list_.drop_duplicates()) # 해당 중복된 항목 중, True인 애들은 drop
print('------------------------------\r\n')  
print(list_.replace('-999',  np.nan)) # 해당하는 값을 치환


     A     B
0  one  -999
1  tow     1
2  one     2
3  tow     2
4  one  -999
5  tow     4
6  tow     4
------------------------------

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool
------------------------------

     A     B
0  one  -999
1  tow     1
2  one     2
3  tow     2
5  tow     4
------------------------------

     A    B
0  one  NaN
1  tow    1
2  one    2
3  tow    2
4  one  NaN
5  tow    4
6  tow    4


In [ ]:
# Row, Col 명 rename

list_ = pd.DataFrame(np.arange(12).reshape((3,4)), index=['A','B','c'], columns=['one','Tow','three','four']) 
list_.index = list_.index.map(lambda x: x[:4].upper()) # 대문자 변경 index
print(list_)
print('------------------------------------------------------------------')
list_2 = pd.DataFrame(np.arange(12).reshape((3,4)), index=['A','B','c'], columns=['one','Tow','three','four']) 
list_2 = list_2.rename(index=str.title, columns = str.upper) # 대문자 변경 다른방식
print(list_2)
print('------------------------------------------------------------------')
list_3 = pd.DataFrame(np.arange(12).reshape((3,4)), index=['A','B','c'], columns=['one','Tow','three','four']) 
list_3.rename(index={'A':'D'}, columns = {'Tow':'five'},inplace = True) # 직접 접근해서 변경
print(list_3)

   one  Tow  three  four
A    0    1      2     3
B    4    5      6     7
C    8    9     10    11
------------------------------------------------------------------
   ONE  TOW  THREE  FOUR
A    0    1      2     3
B    4    5      6     7
C    8    9     10    11
------------------------------------------------------------------
   one  five  three  four
D    0     1      2     3
B    4     5      6     7
c    8     9     10    11


In [ ]:
# 그룹별, 분류
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,36,60,100]

cats = pd.cut(ages, bins)
print(pd.value_counts(cats))

(18, 25]     5
(25, 36]     3
(36, 60]     3
(60, 100]    1
dtype: int64


In [ ]:
dict_1 = {
    'col1': [1, 2, 3, 4, 5],
    'col2': [6, 7, 8, 9, 10],
    'col3': [11, 12, 13, 14, 15],
    'col4': [16, 17, 18, 19, 20]
}
# 하나의 컬럼의 값으로 키값으로 등록할수 있음
list_1 = pd.DataFrame(dict_1)
print(list_1)
print('------------------------------------------------------------------') 
list_2 = list_1.set_index(keys=['col2'], inplace=False, drop=False) # col2를 키값으로
print(list_2)
print('------------------------------------------------------------------') 
list_3 = list_1.set_index(keys=['col1'], inplace=False, drop=True) # col1을 키값으로 drop은 키값으로 사용된 컬럼을 드랍하고 결과값을 가져옴
print(list_3)

   col1  col2  col3  col4
0     1     6    11    16
1     2     7    12    17
2     3     8    13    18
3     4     9    14    19
4     5    10    15    20
------------------------------------------------------------------
      col1  col2  col3  col4
col2                        
6        1     6    11    16
7        2     7    12    17
8        3     8    13    18
9        4     9    14    19
10       5    10    15    20
------------------------------------------------------------------
      col2  col3  col4
col1                  
1        6    11    16
2        7    12    17
3        8    13    18
4        9    14    19
5       10    15    20


In [ ]:
# 데이터 이어붙이기
arr_  = np.arange(12).reshape((3,4)) 
arr_2 = np.concatenate([arr_,arr_], axis=1)
print(arr_2)
print('-----------------------------------------------')

A_1 = pd.Series([0,1], index=['a','b'])
A_2 = pd.Series([2,3,4], index=['c','d','e'])
A_3 = pd.Series([5,6], index=['f','g'])

A_A = pd.concat([A_1,A_2,A_3])
print(A_A)
print('-----------------------------------------------')
A_A_2 = pd.concat([A_1,A_2,A_3], axis = 1) # axis =1 로 설정하면 DataFrame으로 설정됨
print(A_A_2)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]
-----------------------------------------------
a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64
-----------------------------------------------
     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [6]:
# 피벗
list_ = pd.DataFrame(np.arange(6).reshape((2,3)), index = pd.Index(['A','B'], name = 'state'), columns= pd.Index(['one', 'tow','three'], name = 'number'))
print(list_)
print('----------------------------------------------------------')
list_2 = list_.stack()
print(list_2) # stack 피벗 진행
print('----------------------------------------------------------')
print(list_2.unstack()) # 다시 원상복구!
print('----------------------------------------------------------')
print(list_2.unstack(0)) # 컬럼 로우 index 회전

number  one  tow  three
state                  
A         0    1      2
B         3    4      5
----------------------------------------------------------
state  number
A      one       0
       tow       1
       three     2
B      one       3
       tow       4
       three     5
dtype: int64
----------------------------------------------------------
number  one  tow  three
state                  
A         0    1      2
B         3    4      5
----------------------------------------------------------
state   A  B
number      
one     0  3
tow     1  4
three   2  5
