<a href="https://colab.research.google.com/github/JGH94/Python_Pandas/blob/main/Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import patsy
import statsmodels.api as sm
import statsmodels.formula.api as smf
import random
import numpy as np
from numpy import nan as NA  

In [2]:
# 기초 Series, DataFrame
# Series는 1차원 배열 구조 배열에대한 색인을 갖고있음
# DataFrame은 로우와 컬럼에 대한 색인을 가지고 있으며, 파이썬 DIct와 비슷하다
# 색인 객체는 변경이 불가능, reindex를 사용하여 야함 
series = pd.Series([1,5,-5,3])
print(series) 
dataframe = pd.DataFrame({1,5,-5,3})
dataframe

0    1
1    5
2   -5
3    3
dtype: int64


0
0  3
1  1
2 -5
3  5

In [3]:
# excel, Josn 형태의 다양한 형태의 데이터를 사용.. json 형태의 데이터를 받는 형태
import json
json_ = """ {  "name": "WECO",
               "addr": "SEONGNAM",
               "friends" : [{"name" : "J", "AGE" : 29},
                            {"name" : "K", "AGE" : 25}]}"""
a_json = json.loads(json_) # python 형태로 변환 
b_json = json.dumps(a_json)# python 객체를 json형태로 변환
print(a_json,type(a_json))
print(b_json,type(b_json))

# json 형태를 DataFrame으로 가져옴
c_json = pd.DataFrame(a_json['friends'], columns = ["name","AGE"]) 
c_json 

{'name': 'WECO', 'addr': 'SEONGNAM', 'friends': [{'name': 'J', 'AGE': 29}, {'name': 'K', 'AGE': 25}]} <class 'dict'>
{"name": "WECO", "addr": "SEONGNAM", "friends": [{"name": "J", "AGE": 29}, {"name": "K", "AGE": 25}]} <class 'str'>


name  AGE
0    J   29
1    K   25

In [4]:
# null 값 제거 
#Series
print('1.Series') 
Slist_ = pd.Series([1,NA,3,NA,5,NA, 7])
print(Slist_)
print('-------------------------------------------')
print(Slist_.dropna()) 
#DataFrame
print('2.DataFrame') 
Dlist_ = pd.DataFrame([[1,5,3],[1,NA,5],[NA,NA,NA],[NA,5,3]])
print(Dlist_)
print('-------------------------------------------') 
#null 값을 하나라도 포함하면 제거
print('3.null 값을 하나라도 포함하면 제거') 
Dlist_D = Dlist_.dropna();
print(Dlist_D)
print('-------------------------------------------') 
#null 값이 전부인 로우만 제거
print('4. null 값이 전부인 로우만 제거') 
Dlist_R = Dlist_.dropna(how='all')
print(Dlist_R)
print('-------------------------------------------') 
#Col도 적용가능
print('5. Col도 적용가능') 
Dlist_[4] = NA # 4번째 컬럼에 null 값 적용
print(Dlist_)
Dlist_C = Dlist_.dropna(how='all', axis=1)
print(Dlist_C) 

1.Series
0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    NaN
6    7.0
dtype: float64
-------------------------------------------
0    1.0
2    3.0
4    5.0
6    7.0
dtype: float64
2.DataFrame
     0    1    2
0  1.0  5.0  3.0
1  1.0  NaN  5.0
2  NaN  NaN  NaN
3  NaN  5.0  3.0
-------------------------------------------
3.null 값을 하나라도 포함하면 제거
     0    1    2
0  1.0  5.0  3.0
-------------------------------------------
4. null 값이 전부인 로우만 제거
     0    1    2
0  1.0  5.0  3.0
1  1.0  NaN  5.0
3  NaN  5.0  3.0
-------------------------------------------
5. Col도 적용가능
     0    1    2   4
0  1.0  5.0  3.0 NaN
1  1.0  NaN  5.0 NaN
2  NaN  NaN  NaN NaN
3  NaN  5.0  3.0 NaN
     0    1    2
0  1.0  5.0  3.0
1  1.0  NaN  5.0
2  NaN  NaN  NaN
3  NaN  5.0  3.0


In [5]:
# 결측치 
dt_ = pd.DataFrame(np.random.randn(7,3))
dt_.iloc[:4,1] = NA
dt_.iloc[:2,2] = NA
print(dt_)
print('------------------------------\r\n')
print('1. 0으로 채우기')
print(dt_.fillna(0))
print('------------------------------\r\n') 
print('2. 컬럼마다 다른 값 적용')
print(dt_.fillna({1:1, 2:0}))
print('------------------------------\r\n') 
print('3. 평균값')
print(dt_.fillna(dt_.mean(),limit=2)) # limit은 앞의 몇개, 뒤에 몇개부터 값을 채울지 지정

          0         1         2
0 -1.331282       NaN       NaN
1  0.005816       NaN       NaN
2 -0.594659       NaN -0.006727
3  0.186840       NaN -0.352143
4  0.204963  1.372748 -0.138600
5 -0.381325 -0.342488 -1.070243
6  0.738496  0.851180 -1.398370
------------------------------

1. 0으로 채우기
          0         1         2
0 -1.331282  0.000000  0.000000
1  0.005816  0.000000  0.000000
2 -0.594659  0.000000 -0.006727
3  0.186840  0.000000 -0.352143
4  0.204963  1.372748 -0.138600
5 -0.381325 -0.342488 -1.070243
6  0.738496  0.851180 -1.398370
------------------------------

2. 컬럼마다 다른 값 적용
          0         1         2
0 -1.331282  1.000000  0.000000
1  0.005816  1.000000  0.000000
2 -0.594659  1.000000 -0.006727
3  0.186840  1.000000 -0.352143
4  0.204963  1.372748 -0.138600
5 -0.381325 -0.342488 -1.070243
6  0.738496  0.851180 -1.398370
------------------------------

3. 평균값
          0         1         2
0 -1.331282  0.627147 -0.593217
1  0.005816  0.627147 -0.593217
2 -0.5

In [6]:
# 중복제거
list_ = pd.DataFrame({"A":["one","tow"] * 3 + ["tow"],
                      "B":["-999","1","2","2","-999","4","4"]})
print(list_) 
print('------------------------------\r\n')  
print(list_.duplicated())      # 중복인 항목을 Bool 형태로 반환
print('------------------------------\r\n')  
print(list_.drop_duplicates()) # 해당 중복된 항목 중, True인 애들은 drop
print('------------------------------\r\n')  
print(list_.replace('-999',  np.nan)) # 해당하는 값을 치환


     A     B
0  one  -999
1  tow     1
2  one     2
3  tow     2
4  one  -999
5  tow     4
6  tow     4
------------------------------

0    False
1    False
2    False
3    False
4     True
5    False
6     True
dtype: bool
------------------------------

     A     B
0  one  -999
1  tow     1
2  one     2
3  tow     2
5  tow     4
------------------------------

     A    B
0  one  NaN
1  tow    1
2  one    2
3  tow    2
4  one  NaN
5  tow    4
6  tow    4


In [7]:
# Row, Col 명 rename

list_ = pd.DataFrame(np.arange(12).reshape((3,4)), index=['A','B','c'], columns=['one','Tow','three','four']) 
list_.index = list_.index.map(lambda x: x[:4].upper()) # 대문자 변경 index
print(list_)
print('------------------------------------------------------------------')
list_2 = pd.DataFrame(np.arange(12).reshape((3,4)), index=['A','B','c'], columns=['one','Tow','three','four']) 
list_2 = list_2.rename(index=str.title, columns = str.upper) # 대문자 변경 다른방식
print(list_2)
print('------------------------------------------------------------------')
list_3 = pd.DataFrame(np.arange(12).reshape((3,4)), index=['A','B','c'], columns=['one','Tow','three','four']) 
list_3.rename(index={'A':'D'}, columns = {'Tow':'five'},inplace = True) # 직접 접근해서 변경
print(list_3)

   one  Tow  three  four
A    0    1      2     3
B    4    5      6     7
C    8    9     10    11
------------------------------------------------------------------
   ONE  TOW  THREE  FOUR
A    0    1      2     3
B    4    5      6     7
C    8    9     10    11
------------------------------------------------------------------
   one  five  three  four
D    0     1      2     3
B    4     5      6     7
c    8     9     10    11


In [8]:
# 그룹별, 분류
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,36,60,100]

cats = pd.cut(ages, bins)
print(pd.value_counts(cats))

(18, 25]     5
(25, 36]     3
(36, 60]     3
(60, 100]    1
dtype: int64


In [9]:
dict_1 = {
    'col1': [1, 2, 3, 4, 5],
    'col2': [6, 7, 8, 9, 10],
    'col3': [11, 12, 13, 14, 15],
    'col4': [16, 17, 18, 19, 20]
}
# 하나의 컬럼의 값으로 키값으로 등록할수 있음
list_1 = pd.DataFrame(dict_1)
print(list_1)
print('------------------------------------------------------------------') 
list_2 = list_1.set_index(keys=['col2'], inplace=False, drop=False) # col2를 키값으로
print(list_2)
print('------------------------------------------------------------------') 
list_3 = list_1.set_index(keys=['col1'], inplace=False, drop=True) # col1을 키값으로 drop은 키값으로 사용된 컬럼을 드랍하고 결과값을 가져옴
print(list_3)

   col1  col2  col3  col4
0     1     6    11    16
1     2     7    12    17
2     3     8    13    18
3     4     9    14    19
4     5    10    15    20
------------------------------------------------------------------
      col1  col2  col3  col4
col2                        
6        1     6    11    16
7        2     7    12    17
8        3     8    13    18
9        4     9    14    19
10       5    10    15    20
------------------------------------------------------------------
      col2  col3  col4
col1                  
1        6    11    16
2        7    12    17
3        8    13    18
4        9    14    19
5       10    15    20


In [10]:
# 데이터 이어붙이기
arr_  = np.arange(12).reshape((3,4)) 
arr_2 = np.concatenate([arr_,arr_], axis=1)
print(arr_2)
print('-----------------------------------------------')

A_1 = pd.Series([0,1], index=['a','b'])
A_2 = pd.Series([2,3,4], index=['c','d','e'])
A_3 = pd.Series([5,6], index=['f','g'])

A_A = pd.concat([A_1,A_2,A_3])
print(A_A)
print('-----------------------------------------------')
A_A_2 = pd.concat([A_1,A_2,A_3], axis = 1) # axis =1 로 설정하면 DataFrame으로 설정됨
print(A_A_2)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]
-----------------------------------------------
a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64
-----------------------------------------------
     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0


In [11]:
# 피벗
list_ = pd.DataFrame(np.arange(6).reshape((2,3)), index = pd.Index(['A','B'], name = 'state'), columns= pd.Index(['one', 'tow','three'], name = 'number'))
print(list_)
print('----------------------------------------------------------')
list_2 = list_.stack()
print(list_2) # stack 피벗 진행
print('----------------------------------------------------------')
print(list_2.unstack()) # 다시 원상복구!
print('----------------------------------------------------------')
print(list_2.unstack(0)) # 컬럼 로우 index 회전

number  one  tow  three
state                  
A         0    1      2
B         3    4      5
----------------------------------------------------------
state  number
A      one       0
       tow       1
       three     2
B      one       3
       tow       4
       three     5
dtype: int64
----------------------------------------------------------
number  one  tow  three
state                  
A         0    1      2
B         3    4      5
----------------------------------------------------------
state   A  B
number      
one     0  3
tow     1  4
three   2  5


In [12]:
# 데이터 추가 방식
list_ = pd.DataFrame(np.arange(6).reshape((2,3)), index = pd.Index(['A','B']), columns= pd.Index(['one', 'tow','three']))
print(list_)
print('------------------------------------------------------------')
list_['four'] = list_['one'] + list_['tow'] + list_['three']
print(list_)
print('------------------------------------------------------------') 
four_ = list_.groupby(['one','tow'])
print(four_['four'].agg('mean'))
print('------------------------------------------------------------')
grouped_four = list_['four']
print(grouped_four)
print(grouped_four.agg('mean')) 
print(grouped_four.agg(['mean','std']))
print('------------------------------------------------------------') 
fucn = ['count','mean', 'max']
Rlist_ = four_['one','tow'].agg(fucn)
print(Rlist_)

   one  tow  three
A    0    1      2
B    3    4      5
------------------------------------------------------------
   one  tow  three  four
A    0    1      2     3
B    3    4      5    12
------------------------------------------------------------
one  tow
0    1       3.0
3    4      12.0
Name: four, dtype: float64
------------------------------------------------------------
A     3
B    12
Name: four, dtype: int64
7.5
mean    7.500000
std     6.363961
Name: four, dtype: float64
------------------------------------------------------------
          one            tow         
        count mean max count mean max
one tow                              
0   1       1  0.0   0     1  1.0   1
3   4       1  3.0   3     1  4.0   4


<ipython-input-12-e21f043b1cb9>:17: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  Rlist_ = four_['one','tow'].agg(fucn)


In [13]:
list_  = pd.DatetimeIndex(['1/1/2000','1/2/2000','1/2/2000','1/2/2000','1/3/2000']) 
print(list_)
print('---------------------------------------------------------')
# 2 의 중복된 index 값이 다르다.
dup_ts = pd.Series(np.arange(5), index = list_)
print(dup_ts)
# 중복된 값이 있는 지 확인 false면 중복된 값이 있음
dup_ts.index.is_unique 
group_ = dup_ts.groupby(level=0)  
print(group_.mean())
print(group_.count()) 
print('---------------------------------------------------------')
# 날짜 범위 생성
index = pd.date_range('2022-01-01', '2022-02-01')
print(index)
# 2022-01-01 부터 20일 추가
index_2 = pd.date_range(start = '2022-01-01', periods = 20)
print(index_2)
# 2022-01-01 뒤로 20일
index_3 = pd.date_range(end='2022-01-01', periods = 20)
print(index_3)
print('---------------------------------------------------------')
# 시간 추가
t_index = pd.date_range('2022-01-01', '2022-01-07', freq = '8h')
print(t_index)
t_list = pd.Series(np.arange(19), index = t_index) 

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-02', '2000-01-02',
               '2000-01-03'],
              dtype='datetime64[ns]', freq=None)
---------------------------------------------------------
2000-01-01    0
2000-01-02    1
2000-01-02    2
2000-01-02    3
2000-01-03    4
dtype: int64
2000-01-01    0.0
2000-01-02    2.0
2000-01-03    4.0
dtype: float64
2000-01-01    1
2000-01-02    3
2000-01-03    1
dtype: int64
---------------------------------------------------------
DatetimeIndex(['2022-01-01', '2022-01-02', '2022-01-03', '2022-01-04',
               '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08',
               '2022-01-09', '2022-01-10', '2022-01-11', '2022-01-12',
               '2022-01-13', '2022-01-14', '2022-01-15', '2022-01-16',
               '2022-01-17', '2022-01-18', '2022-01-19', '2022-01-20',
               '2022-01-21', '2022-01-22', '2022-01-23', '2022-01-24',
               '2022-01-25', '2022-01-26', '2022-01-27', '2022-01-28',
              

In [14]:
list_ = pd.Series(['apple', 'orange', 'apple','apple'] * 2)
print(list_)
print(pd.value_counts(list_))
print('---------------------------------------------------------')

index_ = pd.Series([0,1,0,0] * 2)
dim = pd.Series(['apple', 'orange']) 
print(index_)
print(dim)
print('---------------------------------------------------------')
print(dim.take(index_))
print('---------------------------------------------------------') 
Fr_ = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(Fr_)
Df_ = pd.DataFrame({ 'fruit':Fr_,'basket_id':np.arange(N), 'count': np.random.randint(3,15,size=N), 'weight': np.random.uniform(0,4,size=N)}, columns = ['basket_id', 'fruit', 'count', 'weight'])
print(Df_)
# 범주형 데이터로 변경
Fr_C = Df_['fruit'].astype('category')
print(Fr_C) 
print('---------------------------------------------------------')
C = Fr_C.values
print(type(C)) 
print(C.categories)
print(C.codes)
print('---------------------------------------------------------') 
Df_['fruit'] = Df_['fruit'].astype('category')
print(Df_.fruit)

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object
apple     6
orange    2
dtype: int64
---------------------------------------------------------
0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64
0     apple
1    orange
dtype: object
---------------------------------------------------------
0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object
---------------------------------------------------------
   basket_id   fruit  count    weight
0          0   apple      6  1.357178
1          1  orange      9  2.482185
2          2   apple      4  0.950804
3          3   apple      3  3.764111
4          4   apple     11  0.234244
5          5  orange     10  3.356934
6          6   apple      9  3.699764
7          7   apple      6  1.032761
0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: cate

In [15]:
# Categorical의 메모리 성능
np.random.seed(12345)
drows_ = np.random.rand(1000)
print(drows_[:5])
print('---------------------------------------------------------')
bins = pd.qcut(drows_, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
print(bins[:10])
print('---------------------------------------------------------') 
bins = pd.Series(bins, name = 'quartitle')
result = (pd.Series(drows_).groupby(bins).agg(['count','min','max']).reset_index())
print(result) 
print('---------------------------------------------------------') 
N = 1000000
draws = pd.Series(np.random.randn(N))
labels = pd.Series(['foo','bar','baz','qux'] * (N//4))
cat = labels.astype('category')
# 같은 데이터여도 categorical 형식은 더 적은 메모리를 사용하고있음
print(labels.memory_usage())
print(cat.memory_usage())

[0.92961609 0.31637555 0.18391881 0.20456028 0.56772503]
---------------------------------------------------------
['Q4', 'Q2', 'Q1', 'Q1', 'Q3', 'Q3', 'Q4', 'Q3', 'Q3', 'Q3']
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']
---------------------------------------------------------
  quartitle  count       min       max
0        Q1    250  0.000107  0.258003
1        Q2    250  0.258719  0.502532
2        Q3    250  0.503929  0.753248
3        Q4    250  0.757735  0.999414
---------------------------------------------------------
8000128
1000332


In [16]:
# Group By
df = pd.DataFrame({'key' :['a','b','c'] * 4, 'value' : np.arange(12.)})
print(df)
df_key = df.groupby('key').value
print('-----------------------------------------') 
print(df_key.mean())
print('-----------------------------------------')
print(df_key.transform(lambda x: x.mean()))
print('-----------------------------------------') 
#내림차순으로
print(df_key.transform(lambda x: x.rank(ascending=False)))
print('-----------------------------------------') 
Num_ = 15
times_ = pd.date_range('2022-01-01 00:00', freq = '5min', periods = Num_)
print(times_)
print('-----------------------------------------') 
df_ = pd.DataFrame({'time' : times_.repeat(3), 'key' : np.tile(['a','b','c'], Num_), 'value' :np.arange(Num_*3)})
print(df_[:7]) 

   key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0
-----------------------------------------
key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64
-----------------------------------------
0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64
-----------------------------------------
0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64
-----------------------------------------
DatetimeIndex(['2022-01-01 00:00:00', '2022-01-01 00:05:00',
               '2022-01-01 00:10:00', '2022-01-01 00:15:00',
               '2022-01-01 00:20:00', '2022-01-01 00:25:00',
               '2022-01-01 00:30:00', '2022-01-01 00:35:00',
               '2022-01-01 00:40:00', '2022-01-01 0

In [17]:
 # Patsy를 활용한 전처리
data_ = pd.DataFrame({'a' : [1,2,3,4,5], 'b':[0.01,-0.01,0.25,-4.1,0], 'c' : [-1.5,0,3.6,1.3,-2]})
print(data_)
print('------------------------------------')
y,X = patsy.dmatrices('c ~a + b', data_)
print(y)
print('------------------------------------') 
print(X)
print('------------------------------------')
print(patsy.dmatrices('c ~ a + b + 0', data_)[1])
print('------------------------------------') 
coef , resid, _, _ = np.linalg.lstsq(X,y)
print(coef)
print('------------------------------------') 
print(resid)

   a     b    c
0  1  0.01 -1.5
1  2 -0.01  0.0
2  3  0.25  3.6
3  4 -4.10  1.3
4  5  0.00 -2.0
------------------------------------
[[-1.5]
 [ 0. ]
 [ 3.6]
 [ 1.3]
 [-2. ]]
------------------------------------
[[ 1.    1.    0.01]
 [ 1.    2.   -0.01]
 [ 1.    3.    0.25]
 [ 1.    4.   -4.1 ]
 [ 1.    5.    0.  ]]
------------------------------------
[[ 1.    0.01]
 [ 2.   -0.01]
 [ 3.    0.25]
 [ 4.   -4.1 ]
 [ 5.    0.  ]]
------------------------------------
[[ 0.31290976]
 [-0.07910564]
 [-0.26546384]]
------------------------------------
[19.63791494]


<ipython-input-17-b7ae5da1c62c>:12: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  coef , resid, _, _ = np.linalg.lstsq(X,y)


In [18]:
# statsmodels  - 데이터 탐색, 시각화를 위한 라이브러리
def dnorm(mean, variance, size = 1):
  if isinstance(size, int):
    size = size,
  return mean + np.sqrt(variance) * np.random.randn(*size)

np.random.seed(12345)
num_ = 100

X_ = np.c_[dnorm(0, 0.4, size = num_),
           dnorm(0, 0.6, size = num_),
           dnorm(0, 0.2, size = num_)]
eps = dnorm(0, 0.1, size = num_)
beta = [0.1, 0.3, 0.5]

Y_ = np.dot(X_, beta) + eps
print(X_[:5])
print('--------------------------------')
print(Y_[:5])
print('--------------------------------')

X_model = sm.add_constant(X_)
print(X_model[:5])

print('--------------------------------')

model = sm.OLS(Y_,X_) # 회귀분석
results_ = model.fit()
results_.params

print(results_.summary()) 
# R-Squared - 데이터에 맞는 정도를 나타내는 지표 중 하나 0~1 사이의 값이며, 0.4 이상이면 괜찮은 모델
# coef (계수) - 데이터로 얻는 계수의 추정치, X의 값이 A만큼 상승할때마다 Y 값이 증가할것이다.  

[[-0.12946849 -1.21275292  0.50422488]
 [ 0.30291036 -0.43574176 -0.25417986]
 [-0.32852189 -0.02530153  0.13835097]
 [-0.35147471 -0.71960511 -0.25821463]
 [ 1.2432688  -0.37379916 -0.52262905]]
--------------------------------
[ 0.42786349 -0.67348041 -0.09087764 -0.48949442 -0.12894109]
--------------------------------
[[ 1.         -0.12946849 -1.21275292  0.50422488]
 [ 1.          0.30291036 -0.43574176 -0.25417986]
 [ 1.         -0.32852189 -0.02530153  0.13835097]
 [ 1.         -0.35147471 -0.71960511 -0.25821463]
 [ 1.          1.2432688  -0.37379916 -0.52262905]]
--------------------------------
                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.430
Model:                            OLS   Adj. R-squared (uncentered):              0.413
Method:                 Least Squares   F-statistic:                              24.42
Date:                Tue, 20 Dec 20

In [19]:
# 지금까지 정리
X_ = np.c_[dnorm(0, 0.4, size = num_),
           dnorm(0, 0.6, size = num_),
           dnorm(0, 0.2, size = num_)]
Y_ = np.dot(X_, beta) + eps
data_ = pd.DataFrame(X_, columns = ['col0', 'col1', 'col2'])
data_['y'] = Y_
print(data_)
print('-------------------------------------')
result_= smf.ols('y ~ col0 + col1 + col2', data = data_).fit()
print(result_.params)
print('-------------------------------------')
print(result_.predict(data_[:5]))
print('-------------------------------------')
print(result_.summary())

        col0      col1      col2         y
0   0.595502 -0.590117  0.339078  0.604578
1   0.337329 -0.256869 -0.230576 -0.604575
2   0.225323 -1.356563 -0.264394 -0.636244
3  -0.006397  0.487139  0.401037  0.236662
4   0.895401  0.218825 -0.434440  0.058154
..       ...       ...       ...       ...
95 -0.035870 -0.097655 -0.395974 -0.189412
96  1.455074  0.308448 -0.572833 -0.268979
97  0.360182  0.109713  0.087703  0.535153
98  0.941985 -0.204603  0.426930  0.198520
99  0.799582 -0.350282 -0.358205 -0.064160

[100 rows x 4 columns]
-------------------------------------
Intercept    0.035031
col0         0.168699
col1         0.294535
col2         0.470331
dtype: float64
-------------------------------------
0    0.121161
1   -0.092166
2   -0.450865
3    0.366052
4    0.046206
dtype: float64
-------------------------------------
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.413


In [33]:
# reshape C, 포트란
arr_ =  np.arange(12).reshape((3,4))
print(arr_)
print('------------')
print(arr_.ravel()) # 가로 순서 (C)
print('------------')
print(arr_.ravel('F')) # 새로 순서 (포트란)
print('------------')
# 이어 붙이기 vstack, hstack
arr_3  = np.array([[1,2,3],[4,5,6]])
arr_4 = np.array([[7,8,9],[10,11,12]])
print('vsatck') 
re_ = np.vstack((arr_3,arr_4)) # 그대로 이어 붙이기
print(re_)
print('------------')
print('hsatck') 
re_ = np.hstack((arr_3,arr_4)) # 인덱스로 합치기
print(re_)
print('------------')
# put 인덱스로 치환
ar_ = np.arange(5)  # [0,1,2,3,4]
np.put(ar_,[0,2],[-11,-22]) # 배열, 치환할 인덱스, 치환할 값으로 넣어주면 됩니다.
ar_ # [-11,1,-22,3,4]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
------------
[ 0  4  8  1  5  9  2  6 10  3  7 11]
------------
vsatck
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
------------
hsatck
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
------------


array([-11,   1, -22,   3,   4])

array([ 0,  4,  8, 12, 16])